// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKAtTExmid3gx8Dj4Sujq3lGUibIAci3Y',
    appId: '1:28348437666:web:a0a44d8b05549ed3ed73fb',
    messagingSenderId: '28348437666',
    projectId: 'mediai-a4ebf',
    authDomain: 'mediai-a4ebf.firebaseapp.com',
    storageBucket: 'mediai-a4ebf.firebasestorage.app',
    measurementId: 'G-YB2ZN9R719',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL2C_pa2dt0d1dK-8JmwTVLBCMOVjprGw',
    appId: '1:28348437666:android:a9b6393d331e7024ed73fb',
    messagingSenderId: '28348437666',
    projectId: 'mediai-a4ebf',
    storageBucket: 'mediai-a4ebf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCd5Va85auCoqlgn6rJTl5VMjGRmKjOdM',
    appId: '1:28348437666:ios:b75b3e6c9e7e6c7ded73fb',
    messagingSenderId: '28348437666',
    projectId: 'mediai-a4ebf',
    storageBucket: 'mediai-a4ebf.firebasestorage.app',
    iosBundleId: 'com.kuzminykhhh.mediai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCd5Va85auCoqlgn6rJTl5VMjGRmKjOdM',
    appId: '1:28348437666:ios:bc2eac702ee4de37ed73fb',
    messagingSenderId: '28348437666',
    projectId: 'mediai-a4ebf',
    storageBucket: 'mediai-a4ebf.firebasestorage.app',
    iosBundleId: 'com.example.mediAi',
  );
}
